<?php
$title = 'Proxy Configuration';
$this->headTitle($title);
?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('config', array('action'=>'add'));?>">Add new Config</a>
 </p>

 <table class="table" border=1>
 <tr>
     <th>Name</th>
     <th>Value</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($configs as $config) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($config['name']);?></td>
     <td><?php echo $this->escapeHtml($config['value']);?></td>
     <td>
         <a href="<?php echo $this->url('config',
             array('action'=>'edit', 'id' => $config['id']));?>">Edit</a>
         <a href="<?php echo $this->url('config',
             array('action'=>'delete', 'id' => $config['id']));?>">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>