<?php echo $this->doctype(); ?>

<html lang="en">
<head>
<meta charset="utf-8">
<?php echo $this->headTitle('Services Gateway '. 'Mock' . 'API')->setSeparator(' - ')->setAutoEscape(false) ?>

<?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

<!-- Le styles -->
<?php /** echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') */ ?>

<!-- Scripts -->
<?php echo $this->headLink()->prependStylesheet($this->basePath() . '/css/layout.css');?>
<?php /* echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
->prependFile($this->basePath() . '/js/jquery-1.7.2.min.js') */
echo $this->headScript();
?>
</head>
<body>

<!-- 
	<div class="container">
		<a href="< ?php echo $this->basePath();?>/"><img alt="Macys QA Dashboard"
			src="http://www1.macys.com/img/nav/co_macysLogo3.gif"></a>
		<div id="navigation">
			< ?php echo $this->navigation('Navigation')->menu(); ?>
		</div>
		<div>
		< ?php echo $this->content; ?>
		<hr>
		</div>
		<footer>
			<p>
				&copy; < ? php echo date('Y'); ?> by Macys, Inc.
				< ? php echo 'All rights reserved.' ?>
			</p>
		</footer>
	</div> -->
	
	<div id="container">
	
	<div id="header">
	<a href="<?php echo $this->basePath();?>/"><img alt="Services Gateway Mock API"
			src="http://www1.macys.com/img/nav/co_macysLogo3.gif"></a>
			</div>
	<div id="navigation">
		<?php echo $this->navigation('Navigation')->menu(); ?>
	</div>
	<div id="content">
		<?php echo $this->content; ?>
	</div>
	<div id="footer">
		<p>
				&copy; <?php echo date('Y'); ?> Services Gateway.
				<?php echo 'All rights reserved.' ?>
			</p>
	</div>
</div>
	
	<!-- /container -->
	<?php echo $this->inlineScript() ?>
</body>
</html>
